# Generated by Django 3.2.16 on 2022-12-21 19:17

import app.enums
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('schedule_time', models.IntegerField()),
                ('time_interval', enumchoicefield.fields.EnumChoiceField(default=app.enums.TimeInterval['five_mins'], enum_class=app.enums.TimeInterval, max_length=9)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
    ]
