# Generated by Django 3.2.16 on 2022-12-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emailschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='time_interval_test',
            field=models.IntegerField(default=5, help_text='Please enter time in minutes'),
        ),
    ]
